// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czuhcymoqjgsmwzimlzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6dWhjeW1vcWpnc213emltbHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MzY0NjksImV4cCI6MjA1MDIxMjQ2OX0.nvo0viqEiF6ONCuesSWNye2FB17m_6N9qOKKxvdkZi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);